const playerData = {
	PLAYER_DB_ID: 'PLAYER_DATA_DB_ID',
	PLAYER_LOGIN: 'PLAYER_DATA_LOGIN',
	PLAYER_EMAIL: 'PLAYER_DATA_EMAIL',
	PLAYER_REG_DATE: 'PLAYER_DATA_REG_DATE',
	PLAYER_LAST_JOIN_DATE: 'PLAYER_DATA_LAST_JOIN_DATE',
};

module.exports.playerData = playerData;
